services:
  phpcbf:
    build:
      dockerfile: docker/app/Dockerfile
      target: php_codesniffer
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        mkdir -p /var/www/tools/phpcs/
        rm -rf /var/www/tools/phpcs/*
        cp -a ~/.composer/. /var/www/tools/phpcs/
        phpcbf
    volumes:
      - ./app/:/var/www:delegated

  phpcs:
    build:
      dockerfile: docker/app/Dockerfile
      target: php_codesniffer
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        mkdir -p /var/www/tools/phpcs/
        rm -rf /var/www/tools/phpcs/*
        cp -a ~/.composer/. /var/www/tools/phpcs/
        phpcs
    volumes:
      - ./app/:/var/www:delegated

  phpstan:
    image: ghcr.io/phpstan/phpstan:2.0.4-php8.4
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        mkdir -p /app/tools/phpstan/
        rm -rf /app/tools/phpstan/*
        cp -a /composer/vendor/phpstan/phpstan/phpstan.phar /app/tools/phpstan/
        phpstan
    volumes:
      - ./app/:/app

  phpunit:
    build:
      dockerfile: docker/app/Dockerfile
      target: phpunit
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        mkdir -p /var/www/tools/phpunit/
        rm -rf /var/www/tools/phpunit/*
        cp -a ~/.composer/. /var/www/tools/phpunit/
        phpunit
    volumes:
      - ./app/:/var/www:delegated
